LDFLAGS+=-lbrcmGLESv2 -lbrcmEGL -lopenmaxil -L$(SDKSTAGE)/opt/vc/src/hello_pi/libs/ilclient -L$(SDKSTAGE)/opt/vc/src/hello_pi/libs/vgfont -L$(SDKSTAGE)/opt/vc/src/hello_pi/libs/revision

include Makefile_base.include

